### ISSUE TITLE
vosk?

### ISSUE THREAD

**Issue by paolofaz** [rhasspy/wyoming-addons#11]
how can I use VOSK on my home assistant core (docker container) installation?
i pulled your VOSK container but I did not understand how set it in home assitant... which port?

**Comment by Corrado-possieri** [comment]
I am also interested in this. Is there a way to run VOSK in home assistant core?

**Comment by paolofaz** [comment]
> I am also interested in this. Is there a way to run VOSK in home assistant core?

Yes i’m using it as docker container
