### ISSUE TITLE
Openwakeword Docker image for ARMv7

### ISSUE THREAD

**Issue by dgarcoe** [rhasspy/wyoming-addons#5]
Would it be possible to have this image uploaded to Dockerhub as in other services? I'm trying to build it myself but I'm getting lots of errors and I'm not sure how to go on...

I think the same would apply too to Whisper.

Many thanks and great work!

**Comment by karliwalti** [comment]
The ARMv7 image is available for piper, but unfortunately not for for whisper
https://hub.docker.com/r/rhasspy/wyoming-piper/tags
https://hub.docker.com/r/rhasspy/wyoming-whisper/tags

**Comment by synesthesiam** [comment]
Version 1.8.0 of the Docker image supports armv7 :slightly_smiling_face:

**Comment by dgarcoe** [comment]
Thank you guys! I've seen that Whisper may be resource intensive so I'll try to use it in other HW meanwhile :)
